### ISSUE TITLE
termnal 终端中文异常退出

### ISSUE THREAD

**Issue by laixiaohuai** [maoqide/kubeutil#1]
你好，我用你的代码，在终端里输入中文，或查看中文，termnal 终端中文异常退出，错误如下：
close 1002 (protocol error): Invalid UTF-8 in text frame
请问你有碰到这个情况 吗？

**Comment by maoqide** [comment]
> 你好，我用你的代码，在终端里输入中文，或查看中文，termnal 终端中文异常退出，错误如下：
> close 1002 (protocol error): Invalid UTF-8 in text frame
> 请问你有碰到这个情况 吗？

我这边中文都是正常的，不知道你那边是不是有什么特殊字符。排查的话 go1.13以上可以用内置的strings. ToValidUTF8 方法把输入输出的字符都转化一下试试看。
https://golang.org/src/strings/strings.go#L637

**Comment by laixiaohuai** [comment]
> > 你好，我用你的代码，在终端里输入中文，或查看中文，termnal 终端中文异常退出，错误如下：
> > close 1002 (protocol error): Invalid UTF-8 in text frame
> > 请问你有碰到这个情况 吗？
> 
> 我这边中文都是正常的，不知道你那边是不是有什么特殊字符。排查的话 go1.13以上可以用内置的strings. ToValidUTF8 方法把输入输出的字符都转化一下试试看。
> https://golang.org/src/strings/strings.go#L637

找到问题了，镜像里需要中文包，不过代码还是要优化，镜像没有中文包的时候 ，输入中文，程序直接退出了。
